openapi: 3.1.0
info:
  title: API server for "Six Cities" project
  version: 2.0.0
tags:
  - name: users
  - name: offers
  - name: comments

paths:
  /users/register:
    post:
      tags:
        - users
      summary: User registration
      description: Registers new user

  /users/login:
    post:
      tags:
        - users
      summary: User authentication
      description: Authenticates user

  /users/logout:
    post:
      tags:
        - users
      summary: User unauthentication
      description: Unauthenticates user

  /users/favorite:
    get:
      tags:
        - users
      summary: User's favorite offers
      description: Returns offers, added to favorites by user
    post:
      tags:
        - users
      summary: Add offer to favorites
      description: Adds offer to favorites
    delete:
      tags:
        - users
      summary: Remove offer from favorites
      description: Removes offer from favorites

  /offers:
    get:
      tags:
        - offers
      summary: Get all offers
      description: Returns offers list

  /offers/create:
    post:
      tags:
        - offers
      summary: Offer creation
      description: Creates new offer

  /offers/{offerId}:
    get:
      tags:
        - offers
      summary: Get detailed offer by ID
      description: Returns specific offer data
    put:
      tags:
        - offers
      summary: Offer editing
      description: Edits offer
    delete:
      tags:
        - offers
      summary: Offer deleting
      description: Deletes offer

  /offers/{offerId}/comments:
    get:
      tags:
        - comments
      summary: Get comments for specified offer
      description: Returns comments for specified offer
    post:
      tags:
        - comments
      summary: Posting comment
      description: Creates new comment for the offer

  /offers/premium/{location}:
    get:
      tags:
        - offer
      summary: Seleted location premium offers
      description: Returns list of premium offer for a city

components:
  schemas:
    createUser:
      type: object
      properties:
        email:
          type: string
          example: keks@htmlacademy.ru
          required: true
        name:
          type: string
          example: Keks
          required: true
        password:
          type: string
          example: 123456
          required: true
        userType:
          type: string
          enum:
            - обычный
            - pro
          required: true
          example: pro
        avatar:
          type: string

    user:
      type: object
      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea
        email:
          type: string
          example: keks@htmlacademy.ru
        name:
          type: string
          example: Keks
        avatar:
          type: string
        userType:
          type: string
          enum:
            - обычный
            - pro

    authorizedUser:
      type: object
      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea
        login:
          type: string
          example: keks@htmlacademy.ru
        password:
          type: string
          example: 123456

    createOffer:
      type: object
      properties:
        name:
          type: string
          required: true
        description:
          type: string
          required: true
        location:
          type: string
          enum:
            - Paris
            - Cologne
            - Brussels
            - Amsterdam
            - Hamburg
            - Dusseldorf
          required: true
        previewImage:
          type: string
          required: true
        photos:
          type: array
          items:
            type: string
        isPremium:
          type: boolean
          required: true
        isFavorite:
          type: boolean
          required: true
        type:
          type: string
          enum:
            - apartment
            - house
            - room
            - hotel
          required: true
        numberOfRooms:
          type: integer
          required: true
        numberOfGuests:
          type: integer
          required: true
        price:
          type: number
          required: true
        commodities:
          type: array
          items:
            type: string
            enum:
              - Breakfast
              - Air conditioning
              - Laptop friendly workspace
              - Baby seat
              - Washer
              - Towels
              - Fridge
          required: true
        userId:
          type: string
          required: true

    updateOffer:
      type: object
      properties:
        name:
          type: string
          required: true
        description:
          type: string
          required: true
        location:
          type: string
          enum:
            - Paris
            - Cologne
            - Brussels
            - Amsterdam
            - Hamburg
            - Dusseldorf
          required: true
        previewImage:
          type: string
          required: true
        photos:
          type: array
          items:
            type: string
        isPremium:
          type: boolean
          required: true
        isFavorite:
          type: boolean
          required: true
        type:
          type: string
          enum:
            - apartment
            - house
            - room
            - hotel
          required: true
        numberOfRooms:
          type: integer
          required: true
        numberOfGuests:
          type: integer
          required: true
        price:
          type: number
          required: true
        commodities:
          type: array
          items:
            type: string
            enum:
              - Breakfast
              - Air conditioning
              - Laptop friendly workspace
              - Baby seat
              - Washer
              - Towels
              - Fridge
          required: true
        userId:
          type: string
          required: true
        coordinates:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: number

    offer:
      type: object
      properties:
        name:
          type: string
          required: true
        description:
          type: string
          required: true
        date:
          type: string
          format: date-time
        location:
          type: string
          enum:
            - Paris
            - Cologne
            - Brussels
            - Amsterdam
            - Hamburg
            - Dusseldorf
          required: true
        previewImage:
          type: string
          required: true
        photos:
          type: array
          items:
            type: string
        isPremium:
          type: boolean
          required: true
        isFavorite:
          type: boolean
          required: true
        rating:
          type: number
        type:
          type: string
          enum:
            - apartment
            - house
            - room
            - hotel
          required: true
        numberOfRooms:
          type: integer
          required: true
        numberOfGuests:
          type: integer
          required: true
        price:
          type: number
          required: true
        commodities:
          type: array
          items:
            type: string
            enum:
              - Breakfast
              - Air conditioning
              - Laptop friendly workspace
              - Baby seat
              - Washer
              - Towels
              - Fridge
          required: true
        userId:
          type: string
          required: true
        numberOfComments:
          type: integer
        coordinates:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: number

    createComment:
      type: object
      properties:
        text:
          type: string
          required: true
        rating:
          type: number
          required: true
        user:
          $ref: '#/components/schemas/user'

    comment:
      type: object
      properties:
        text:
          type: string
        date:
          type: string
          format: date-time
        rating:
          type: number
        user:
          $ref: '#/components/schemas/user'
